[profile.default]
solc = "0.8.33"
via_ir = true
optimizer = true
optimizer_runs = 20

# Override with FOUNDRY_ETH_RPC_URL env var for faster RPC.
eth_rpc_url = "https://ethereum-rpc.publicnode.com"
fork_block_number = 24_557_000

[profile.default.optimizer_details]
yul = false
